server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

fdfs:
  tracker-list:
  - 192.168.137.141:22122
  connect-timeout: 2500
  so-timeout: 2500
  thumb-image:
    width: 60
    height: 60

ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
    - image/jpeg
    - image/png
    - image/bmp